steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']   
    options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  # Update Image Tags
  - id: 'Setting Init Image Tag'
    name: ubuntu
    args: ['bash','-c','sed -i "s,INIT_IMAGE_NAME,gcr.io/$PROJECT_ID/hello," kubernetes/app-dev.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/app-dev.yaml', '--validate=false']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=redis-services-cluster'
images: ['gcr.io/$PROJECT_ID/hello']
